openapi: 3.0.0
info:
  title: 'PHP-Slim 4 Tutorial'
  version: '0.1'
servers:
  -
    url: 'http://localhost:28081'
paths:
  '/users/{id}':
    get:
      tags:
        - user
      operationId: getUser
      parameters:
        -
          name: id
          in: path
          description: 'User id'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Read single user'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    UserReaderData:
      title: User
      description: 'A simple user model.'
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          example: 1
        username:
          type: string
          example: johndoe
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        email:
          type: string
          example: johndoe@example.com
      type: object
