name: Lint and Test

on:
  pull_request:

jobs:
  lint_php:
    name: Lint PHP Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP 7.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer lint

      - name: Notify Result to Slack
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':php: *Lint check*'
          channel: '#ci_my_projects'
          url: ${{ secrets.SLACK_WEBHOOK }}

  analyse:
    name: Analyse PHP Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP 7.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer analyse

      - name: Notify Result to Slack
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':php: *Lint check*'
          channel: '#ci_my_projects'
          url: ${{ secrets.SLACK_WEBHOOK }}

  lint_except_php:
    name: Lint Except PHP Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_MD: true
          VALIDATE_BASH: true
          VALIDATE_DOCKER: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Result to Slack
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':github: *Super-Linter check*'
          channel: '#ci_my_projects'
          url: ${{ secrets.SLACK_WEBHOOK }}

  test:
    name: PHP Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP 7.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Test with phpunit
        env:
          APP_ENV: ci
        run: |
          composer test

      - name: Notify Result to Slack
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':php: *Test*'
          channel: '#ci_my_projects'
          url: ${{ secrets.SLACK_WEBHOOK }}
